github:
  description: ":fire: Seata is an easy-to-use, high-performance, open source distributed transaction solution."
  homepage: https://seata.apache.org/
  labels:
    - "mode: AT"
    - "mode: TCC"
    - "mode: SAGA"
    - "mode: XA"
  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  false
  dependabot_alerts:  true
  dependabot_updates: false
  protected_branches:
    master:
      required_status_checks:
        strict: true
        contexts:
          - Required
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 1
    develop:
      required_status_checks:
        strict: true
        contexts:
          - Required
        required_pull_request_reviews:
          dismiss_stale_reviews: true
          required_approving_review_count: 1
    2.x:
      required_status_checks:
        strict: true
        contexts:
          - Required
        required_pull_request_reviews:
          dismiss_stale_reviews: true
          required_approving_review_count: 1
  notifications:
    commits: notifications@seata.apache.org
    issues: dev@seata.apache.org
    pullrequests: dev@seata.apache.org
    discussions: dev@seata.apache.org