codecov:
  require_ci_to_pass: yes
coverage:
  status:
    patch:
      default:
        threshold: 1%
    project: yes
    changes: no
  precision: 2
  range: "50...100"
ignore:
- "codec/seata-codec-protobuf/src/main/java/io/seata/codec/protobuf/generated"
- "test/.*"
- ".github/.*"
- ".mvn/.*"
- ".style/.*"
- "*.md"
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no