#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# application.yml
server:
  tomcat:
    connection-timeout: 60000
    threads:
      max: 200
      min-spare: 10
    accept-count: 200
    max-http-form-post-size: 104857600
  port: 8081

spring:
  application:
    name: seata-namingserver
logging:
  config: classpath:logback-spring.xml
  file:
    path: ${log.home:${user.home}/logs/seata}
heartbeat:
  threshold: 90000
  period: 60000
console:
  user:
    password: seata
    username: seata
seata:
  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    csrf-ignore-urls: /naming/v1/**,/api/v1/naming/**
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login,/version.json,/naming/v1/health,/error

  # MCP Server Configuration
  mcp:
    # Server name (do not set the default to seata-mcp-server)
    serverName: seata-mcp-server
    serverVersion: 2.0.0
    # MCP service transmission types, available in sse and streamable
    mcpType: streamable

    # sse type properties
#    sse:
#      # SSE endpoint (no default/SSE set)
#      sseEndpoint: /sse
#      # message endpoint (no default /message set)
#      messageEndpoint: /message

    # streamable type properties
    streamable:
      mcpEndpoint: /mcp
      heartBeatSecondDuration: 30

    # Query limits the maximum time interval, The unit is milliseconds, Default seven days
    query:
      max_query_duration: 604800000
    # Whether to enable permission authentication
    auth:
      enabled: true

  # Business data source configuration
  businessDataSources:
    dataSource1:
      # Whether this data source is enabled
      enabled: true
      dbType: mysql
      driverClassName: com.mysql.cj.jdbc.Driver # Currently, only mysql is supported
      url:
      username: root
      password: root
      datasource: druid # Optional connection pool type (druid/hikari/dbcp)
      minConn: 5
      maxConn: 50
      maxWait: 5000
    dataSource2:
      enabled: true
      dbType: mysql
      driverClassName: com.mysql.cj.jdbc.Driver
      url:
      username: root
      password: root
      datasource: dbcp
      minConn: 5
      maxConn: 50
      maxWait: 5000