server:
  port: 9091

logging:
  config: classpath:logback.xml
  file:
    path: ${user.home}/logs

seata:
  config:
    type: file
    nacos:
      serverAddr: 127.0.0.1:8848
      namespace:
      group: SEATA_GROUP
      username:
      password:
      dataId: seataServer.properties
    consul:
      serverAddr: 127.0.0.1:8500
      aclToken:
    apollo:
      appId: seata-server
      apolloMeta: http://192.168.1.204:8801
      apolloConfigService: http://192.168.1.204:8080
      namespace: application
      apolloAccesskeySecret:
      cluster: seata
    zk:
      serverAddr: 127.0.0.1:2181
      sessionTimeout: 6000
      connectTimeout: 2000
      username:
      password:
      nodePath: /seata/seata.properties
    etcd3:
      serverAddr: http://localhost:2379
  registry:
    type: file
    nacos:
      application: seata-server
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      cluster: default
      username:
      password:
    eureka:
      serviceUrl: http://localhost:8761/eureka
      application: default
      weight: 1
    redis:
      serverAddr: localhost:6379
      db: 0
      password:
      cluster: default
      timeout: 0
    zk:
      cluster: default
      serverAddr: 127.0.0.1:2181
      sessionTimeout: 6000
      connectTimeout: 2000
      username: ""
      password: ""
    consul:
      cluster: default
      serverAddr: 127.0.0.1:8500
      aclToken:
    etcd3:
      cluster: default
      serverAddr: http://localhost:2379
    sofa:
      serverAddr: 127.0.0.1:9603
      application: default
      region: DEFAULT_ZONE
      datacenter: DefaultDataCenter
      cluster: default
      group: SEATA_GROUP
      addressWaitTime: 3000

  server:
    maxCommitRetryTimeout: -1
    maxRollbackRetryTimeout: -1
    rollbackRetryTimeoutUnlockEnable: false
    recovery:
      committingRetryPeriod: 1000
      asynCommittingRetryPeriod: 1000
      rollbackingRetryPeriod: 1000
      timeoutRetryPeriod: 1000
    undo:
      logSaveDays: 7
      logDeletePeriod: 86400000
  store:
    mode: file
    file:
      dir: sessionStore
      maxBranchSessionSize: 16384
      maxGlobalSessionSize: 512
      fileWriteBufferCacheSize: 16384
      sessionReloadReadSize: 100
      flushDiskMode: async
    db:
      datasource: druid
      dbType: mysql
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/seata?rewriteBatchedStatements=true
      user: mysql
      password: mysql
      minConn: 5
      maxConn: 100
      globalTable: global_table
      branchTable: branch_table
      lockTable: lock_table
      queryLimit: 100
      maxWait: 5000
    redis:
      mode: single
      database: 0
      minConn: 1
      maxConn: 10
      password:
      maxTotal: 100
      queryLimit: 100
      sigle:
        host: 127.0.0.1
        port: 6379
      sentinel:
        masterName:
        sentinelHosts:
  metrics:
    enabled: false
    registryType: compact
    exporterList: prometheus
    exporterPrometheusPort: 9898