server:
  port: 9091

logging:
  config: classpath:logback.xml
  file:
    path: ${user.home}/logs

seata:
  store:
    mode: file
    file:
      dir: sessionStore
      maxBranchSessionSize: 16384
      maxGlobalSessionSize: 512
      fileWriteBufferCacheSize: 16384
      sessionReloadReadSize: 100
      flushDiskMode: async
  metrics:
    enabled: false
    registryType: compact
    exporterList: prometheus
    exporterPrometheusPort: 9898



