server:
  port: 9091

logging:
  config: classpath:logback.xml
  file:
    path: ${user.home}/logs

seata:
  config:
    # support: nacos 、 consul 、 apollo 、 zk  、 etcd3
    type: file
  registry:
    # support: nacos 、 eureka 、 redis 、 zk  、 consul 、 etcd3 、 sofa
    type: file
  store:
    # support: file 、 db 、 redis
    mode: file
