-- String type
create table T_DATA_TYPE_STRING_TEST
(
    id             NUMBER,
    CHAR_TEST      CHAR(10)    default '',
    NCHAR_TEST     NCHAR(20)   default '',
    VARCHAR_TEST   VARCHAR(30) default '',
    VARCHAR2_TEST  VARCHAR2(40) default '',
    NVARCHAR2_TEST NVARCHAR2(50) default ''
);
--主键
ALTER TABLE T_DATA_TYPE_STRING_TEST
    ADD CONSTRAINT PK_T_DATA_TYPE_STRING_TEST PRIMARY KEY (id);

-- number
create table T_DATA_TYPE_NUMBER_TEST
(
    id             NUMBER,
    TINYINT_TEST   NUMBER(3,0),
    MEDUIMINT_TEST NUMBER(7,0),
    INT_TEST       NUMBER(10,0),
    BIGINT_TEST    NUMBER(20,0),
    SMALLINT_TEST  NUMBER(38,0),
    INTEGER_TEST   INTEGER(38,0),
    DECIMAL_TEST   DECIMAL(38, 0),
    NUMERIC_TEST   NUMERIC(38, 0),
    DEC_TEST       DEC(38, 0)
);
--主键
ALTER TABLE T_DATA_TYPE_NUMBER_TEST
    ADD CONSTRAINT PK_T_DATA_TYPE_NUMBER_TEST PRIMARY KEY (id);

-- date
create table T_DATA_TYPE_DATE_TEST
(
    id             NUMBER,
    DATE_TEST      DATE,
    TIME_TEST      TIME,
    TIMESTAMP_TEST TIMESTAMP
);
-- binary
create table T_DATA_TYPE_BINARY_TEST
(
    id         NUMBER,
    BLOB_TEST  BLOB,
    CLOB_TEST  CLOB,
    NCLOB_TEST NCLOB,
    BFILE_TEST BFILE,
    RAW_TEST   RAW
);
--主键
ALTER TABLE T_DATA_TYPE_NUMBER_TEST
    ADD CONSTRAINT PK_T_DATA_TYPE_NUMBER_TEST PRIMARY KEY (id);