/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.seata.rm.datasource.xa;

import org.apache.seata.rm.datasource.exec.StatementCallback;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.MockedStatic;
import org.mockito.Mockito;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.any;;
import static org.mockito.Mockito.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import static org.mockito.Mockito.verify;

/**
 * Tests for StatementProxyXA
 */
public class StatementProxyXATest {

    private AbstractConnectionProxyXA mockConnectionProxyXA;
    private Statement mockStatement;
    private MockedStatic<ExecuteTemplateXA> mockedStaticExecuteTemplateXA;

    private StatementProxyXA statementProxyXA;

    @BeforeEach
    public void setUp() {
        mockConnectionProxyXA = mock(AbstractConnectionProxyXA.class);
        mockStatement = mock(Statement.class);
        mockedStaticExecuteTemplateXA = mockStatic(ExecuteTemplateXA.class);

        statementProxyXA = new StatementProxyXA(mockConnectionProxyXA, mockStatement);
    }

    @AfterEach
    public void afterEach() {
        mockedStaticExecuteTemplateXA.close();
    }

    @Test
    public void testExecuteUpdate() throws SQLException {
        String sql = "UPDATE test SET name = 'test' WHERE id = 1";
        when(ExecuteTemplateXA.execute(eq(mockConnectionProxyXA), any(), eq(mockStatement), eq(sql))).thenReturn(1);

        int actualResult = statementProxyXA.executeUpdate(sql);

        assertEquals(1, actualResult);
        StatementCallback<Integer, Statement> capturedCallback = captureStatementCallback(sql);
        // Verify that the captured callback works as expected
        when(mockStatement.executeUpdate(sql)).thenReturn(1);
        int callbackResult = capturedCallback.execute(mockStatement, new Object[]{sql});
        assertEquals(1, callbackResult);
    }

    @Test
    public void testExecuteUpdateWithAutoGeneratedKeys() throws SQLException {
        String sql = "UPDATE test SET name = 'test' WHERE id = 1";
        when(ExecuteTemplateXA.execute(eq(mockConnectionProxyXA), any(), eq(mockStatement), eq(sql), eq(Statement.RETURN_GENERATED_KEYS))).thenReturn(1);

        int actualResult = statementProxyXA.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);

        assertEquals(1, actualResult);
        StatementCallback<Integer, Statement> capturedCallback = captureStatementCallback(sql, Statement.RETURN_GENERATED_KEYS);
        // Verify that the captured callback works as expected
        when(mockStatement.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS)).thenReturn(1);
        int callbackResult = capturedCallback.execute(mockStatement, new Object[]{sql, Statement.RETURN_GENERATED_KEYS});
        assertEquals(1, callbackResult);
    }

    @Test
    public void testExecuteUpdateWithColumnIndexes() throws SQLException {
        String sql = "UPDATE test SET name = 'test' WHERE id = 1";
        int[] columnIndexes = {1};
        when(ExecuteTemplateXA.execute(eq(mockConnectionProxyXA), any(), eq(mockStatement), eq(sql), eq(columnIndexes))).thenReturn(1);

        int actualResult = statementProxyXA.executeUpdate(sql, columnIndexes);

        assertEquals(1, actualResult);
        StatementCallback<Integer, Statement> capturedCallback = captureStatementCallback(sql, columnIndexes);
        // Verify that the captured callback works as expected
        when(mockStatement.executeUpdate(sql, columnIndexes)).thenReturn(1);
        int callbackResult = capturedCallback.execute(mockStatement, new Object[]{sql, columnIndexes});
        assertEquals(1, callbackResult);
    }

    @Test
    public void testExecuteUpdateWithColumnNames() throws SQLException {
        String sql = "UPDATE test SET name = 'test' WHERE id = 1";
        String[] columnNames = {"name"};
        when(ExecuteTemplateXA.execute(eq(mockConnectionProxyXA), any(), eq(mockStatement), eq(sql), eq(columnNames))).thenReturn(1);

        int actualResult = statementProxyXA.executeUpdate(sql, columnNames);

        assertEquals(1, actualResult);
        StatementCallback<Integer, Statement> capturedCallback = captureStatementCallback(sql, columnNames);
        // Verify that the captured callback works as expected
        when(mockStatement.executeUpdate(sql, columnNames)).thenReturn(1);
        int callbackResult = capturedCallback.execute(mockStatement, new Object[]{sql, columnNames});
        assertEquals(1, callbackResult);
    }

    @Test
    public void testExecute() throws SQLException {
        String sql = "SELECT * FROM test WHERE id = 1";
        when(ExecuteTemplateXA.execute(eq(mockConnectionProxyXA), any(), eq(mockStatement), eq(sql))).thenReturn(true);

        boolean actualResult = statementProxyXA.execute(sql);

        assertTrue(actualResult);
        StatementCallback<Boolean, Statement> capturedCallback = captureStatementCallback(sql);
        // Verify that the captured callback works as expected
        when(mockStatement.execute(sql)).thenReturn(true);
        boolean callbackResult = capturedCallback.execute(mockStatement, new Object[]{sql});
        assertTrue(callbackResult);
    }

    @Test
    public void testExecuteWithAutoGeneratedKeys() throws SQLException {
        String sql = "SELECT * FROM test WHERE id = 1";
        when(ExecuteTemplateXA.execute(eq(mockConnectionProxyXA), any(), eq(mockStatement), eq(sql), eq(Statement.RETURN_GENERATED_KEYS))).thenReturn(true);

        boolean actualResult = statementProxyXA.execute(sql, Statement.RETURN_GENERATED_KEYS);

        assertTrue(actualResult);
        StatementCallback<Boolean, Statement> capturedCallback = captureStatementCallback(sql, Statement.RETURN_GENERATED_KEYS);
        // Verify that the captured callback works as expected
        when(mockStatement.execute(sql, Statement.RETURN_GENERATED_KEYS)).thenReturn(true);
        boolean callbackResult = capturedCallback.execute(mockStatement, new Object[]{sql, Statement.RETURN_GENERATED_KEYS});
        assertTrue(callbackResult);
    }

    @Test
    public void testExecuteWithColumnIndexes() throws SQLException {
        String sql = "UPDATE test SET name = 'test' WHERE id = 1";
        int[] columnIndexes = {1};
        when(ExecuteTemplateXA.execute(eq(mockConnectionProxyXA), any(), eq(mockStatement), eq(sql), eq(columnIndexes))).thenReturn(true);

        boolean actualResult = statementProxyXA.execute(sql, columnIndexes);

        assertTrue(actualResult);
        StatementCallback<Boolean, Statement> capturedCallback = captureStatementCallback(sql, columnIndexes);
        // Verify that the captured callback works as expected
        when(mockStatement.execute(sql, columnIndexes)).thenReturn(true);
        boolean callbackResult = capturedCallback.execute(mockStatement, new Object[]{sql, columnIndexes});
        assertTrue(callbackResult);
    }

    @Test
    public void testExecuteWithColumnNames() throws SQLException {
        String sql = "UPDATE test SET name = 'test' WHERE id = 1";
        String[] columnNames = {"name"};
        when(ExecuteTemplateXA.execute(eq(mockConnectionProxyXA), any(), eq(mockStatement), eq(sql), eq(columnNames))).thenReturn(true);

        boolean actualResult = statementProxyXA.execute(sql, columnNames);

        assertTrue(actualResult);
        StatementCallback<Boolean, Statement> capturedCallback = captureStatementCallback(sql, columnNames);
        // Verify that the captured callback works as expected
        when(mockStatement.execute(sql, columnNames)).thenReturn(true);
        boolean callbackResult = capturedCallback.execute(mockStatement, new Object[]{sql, columnNames});
        assertTrue(callbackResult);
    }

    @Test
    public void testExecuteQuery() throws SQLException {
        String sql = "SELECT * FROM test WHERE id = 1";
        ResultSet expectedResultSet = mock(ResultSet.class);
        when(ExecuteTemplateXA.execute(eq(mockConnectionProxyXA), any(), eq(mockStatement), eq(sql))).thenReturn(expectedResultSet);

        ResultSet actualResult = statementProxyXA.executeQuery(sql);

        assertSame(expectedResultSet, actualResult);
        StatementCallback<ResultSet, Statement> capturedCallback = captureStatementCallback(sql);
        // Verify that the captured callback works as expected
        when(mockStatement.executeQuery(sql)).thenReturn(expectedResultSet);
        ResultSet callbackResult = capturedCallback.execute(mockStatement, new Object[]{sql});
        assertSame(expectedResultSet, callbackResult);
    }

    @Test
    public void testExecuteBatch() throws SQLException {
        int[] expectedResult = new int[]{1, 2, 3};
        when(ExecuteTemplateXA.execute(eq(mockConnectionProxyXA), any(), eq(mockStatement))).thenReturn(expectedResult);

        int[] actualResult = statementProxyXA.executeBatch();

        assertEquals(expectedResult, actualResult);
        StatementCallback<int[], Statement> capturedCallback = captureStatementCallback();
        // Verify that the captured callback works as expected
        when(mockStatement.executeBatch()).thenReturn(expectedResult);
        int[] callbackResult = capturedCallback.execute(mockStatement, new Object[]{});
        assertEquals(expectedResult, callbackResult);
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    private StatementCallback captureStatementCallback(Object... args) {
        ArgumentCaptor<StatementCallback> statementCallbackCaptor = ArgumentCaptor.forClass(StatementCallback.class);
        mockedStaticExecuteTemplateXA.verify(() -> ExecuteTemplateXA.execute(
                eq(mockConnectionProxyXA),
                statementCallbackCaptor.capture(),
                eq(mockStatement),
                eq(args))
        );
        return statementCallbackCaptor.getValue();
    }

    @Test
    public void testClose() throws SQLException {
        statementProxyXA.close();

        verify(mockStatement).close();
    }

    @Test
    public void testGetMaxFieldSize() throws SQLException {
        when(mockStatement.getMaxFieldSize()).thenReturn(100);

        int result = statementProxyXA.getMaxFieldSize();

        assertEquals(100, result);
        verify(mockStatement).getMaxFieldSize();
    }

    @Test
    public void testSetMaxFieldSize() throws SQLException {
        statementProxyXA.setMaxFieldSize(200);

        verify(mockStatement).setMaxFieldSize(200);
    }

    @Test
    public void testGetMaxRows() throws SQLException {
        when(mockStatement.getMaxRows()).thenReturn(1000);

        int result = statementProxyXA.getMaxRows();

        assertEquals(1000, result);
        verify(mockStatement).getMaxRows();
    }

    @Test
    public void testSetMaxRows() throws SQLException {
        statementProxyXA.setMaxRows(2000);

        verify(mockStatement).setMaxFieldSize(2000); // Note: there's a bug in the original code
    }

    @Test
    public void testSetEscapeProcessing() throws SQLException {
        statementProxyXA.setEscapeProcessing(true);

        verify(mockStatement).setEscapeProcessing(true);
    }

    @Test
    public void testGetQueryTimeout() throws SQLException {
        when(mockStatement.getQueryTimeout()).thenReturn(30);

        int result = statementProxyXA.getQueryTimeout();

        assertEquals(30, result);
        verify(mockStatement).getQueryTimeout();
    }

    @Test
    public void testSetQueryTimeout() throws SQLException {
        statementProxyXA.setQueryTimeout(60);

        verify(mockStatement).setQueryTimeout(60);
    }

    @Test
    public void testCancel() throws SQLException {
        statementProxyXA.cancel();

        verify(mockStatement).cancel();
    }

    @Test
    public void testGetWarnings() throws SQLException {
        SQLWarning mockWarning = Mockito.mock(SQLWarning.class);
        when(mockStatement.getWarnings()).thenReturn(mockWarning);

        SQLWarning result = statementProxyXA.getWarnings();

        assertEquals(mockWarning, result);
        verify(mockStatement).getWarnings();
    }

    @Test
    public void testClearWarnings() throws SQLException {
        statementProxyXA.clearWarnings();

        verify(mockStatement).clearWarnings();
    }

    @Test
    public void testSetCursorName() throws SQLException {
        statementProxyXA.setCursorName("cursor1");

        verify(mockStatement).setCursorName("cursor1");
    }

    @Test
    public void testGetResultSet() throws SQLException {
        ResultSet mockResultSet = Mockito.mock(ResultSet.class);
        when(mockStatement.getResultSet()).thenReturn(mockResultSet);

        ResultSet result = statementProxyXA.getResultSet();

        assertEquals(mockResultSet, result);
        verify(mockStatement).getResultSet();
    }

    @Test
    public void testGetUpdateCount() throws SQLException {
        when(mockStatement.getUpdateCount()).thenReturn(5);

        int result = statementProxyXA.getUpdateCount();

        assertEquals(5, result);
        verify(mockStatement).getUpdateCount();
    }

    @Test
    public void testGetMoreResults() throws SQLException {
        when(mockStatement.getMoreResults()).thenReturn(true);

        boolean result = statementProxyXA.getMoreResults();

        Assertions.assertTrue(result);
        verify(mockStatement).getMoreResults();
    }

    @Test
    public void testSetFetchDirection() throws SQLException {
        statementProxyXA.setFetchDirection(ResultSet.FETCH_FORWARD);

        verify(mockStatement).setFetchDirection(ResultSet.FETCH_FORWARD);
    }

    @Test
    public void testGetFetchDirection() throws SQLException {
        when(mockStatement.getFetchDirection()).thenReturn(ResultSet.FETCH_FORWARD);

        int result = statementProxyXA.getFetchDirection();

        assertEquals(ResultSet.FETCH_FORWARD, result);
        verify(mockStatement).getFetchDirection();
    }

    @Test
    public void testSetFetchSize() throws SQLException {
        statementProxyXA.setFetchSize(100);

        verify(mockStatement).setFetchSize(100);
    }

    @Test
    public void testGetFetchSize() throws SQLException {
        when(mockStatement.getFetchSize()).thenReturn(100);

        int result = statementProxyXA.getFetchSize();

        assertEquals(100, result);
        verify(mockStatement).getFetchSize();
    }

    @Test
    public void testGetResultSetConcurrency() throws SQLException {
        when(mockStatement.getResultSetConcurrency()).thenReturn(ResultSet.CONCUR_READ_ONLY);

        int result = statementProxyXA.getResultSetConcurrency();

        assertEquals(ResultSet.CONCUR_READ_ONLY, result);
        verify(mockStatement).getResultSetConcurrency();
    }

    @Test
    public void testGetResultSetType() throws SQLException {
        when(mockStatement.getResultSetType()).thenReturn(ResultSet.TYPE_FORWARD_ONLY);

        int result = statementProxyXA.getResultSetType();

        assertEquals(ResultSet.TYPE_FORWARD_ONLY, result);
        verify(mockStatement).getResultSetType();
    }

    @Test
    public void testAddBatch() throws SQLException {
        String sql = "INSERT INTO test (name) VALUES ('test')";
        statementProxyXA.addBatch(sql);

        verify(mockStatement).addBatch(sql);
    }

    @Test
    public void testClearBatch() throws SQLException {
        statementProxyXA.clearBatch();

        verify(mockStatement).clearBatch();
    }

    @Test
    public void testGetConnection() throws SQLException {
        Connection mockConnection = Mockito.mock(Connection.class);
        when(mockStatement.getConnection()).thenReturn(mockConnection);

        Connection result = statementProxyXA.getConnection();

        assertEquals(mockConnection, result);
        verify(mockStatement).getConnection();
    }

    @Test
    public void testGetMoreResultsWithCurrent() throws SQLException {
        when(mockStatement.getMoreResults(Statement.CLOSE_CURRENT_RESULT))
                .thenReturn(true);

        boolean result = statementProxyXA.getMoreResults(Statement.CLOSE_CURRENT_RESULT);

        assertTrue(result);
        verify(mockStatement).getMoreResults(Statement.CLOSE_CURRENT_RESULT);
    }

    @Test
    public void testGetGeneratedKeys() throws SQLException {
        ResultSet mockResultSet = Mockito.mock(ResultSet.class);
        when(mockStatement.getGeneratedKeys()).thenReturn(mockResultSet);

        ResultSet result = statementProxyXA.getGeneratedKeys();

        assertEquals(mockResultSet, result);
        verify(mockStatement).getGeneratedKeys();
    }

    @Test
    public void testGetResultSetHoldability() throws SQLException {
        when(mockStatement.getResultSetHoldability()).thenReturn(ResultSet.CLOSE_CURSORS_AT_COMMIT);

        int result = statementProxyXA.getResultSetHoldability();

        assertEquals(ResultSet.CLOSE_CURSORS_AT_COMMIT, result);
        verify(mockStatement).getResultSetHoldability();
    }

    @Test
    public void testIsClosed() throws SQLException {
        when(mockStatement.isClosed()).thenReturn(false);

        boolean result = statementProxyXA.isClosed();

        assertFalse(result);
        verify(mockStatement).isClosed();
    }

    @Test
    public void testSetPoolable() throws SQLException {
        statementProxyXA.setPoolable(true);

        verify(mockStatement).setPoolable(true);
    }

    @Test
    public void testIsPoolable() throws SQLException {
        when(mockStatement.isPoolable()).thenReturn(true);

        boolean result = statementProxyXA.isPoolable();

        assertTrue(result);
        verify(mockStatement).isPoolable();
    }

    @Test
    public void testCloseOnCompletion() throws SQLException {
        statementProxyXA.closeOnCompletion();

        verify(mockStatement).closeOnCompletion();
    }

    @Test
    public void testIsCloseOnCompletion() throws SQLException {
        when(mockStatement.isCloseOnCompletion()).thenReturn(true);

        boolean result = statementProxyXA.isCloseOnCompletion();

        assertTrue(result);
        verify(mockStatement).isCloseOnCompletion();
    }

    @Test
    public void testUnwrap() throws SQLException {
        when(mockStatement.unwrap(String.class)).thenReturn("test");

        String result = statementProxyXA.unwrap(String.class);

        assertEquals("test", result);
        verify(mockStatement).unwrap(String.class);
    }

    @Test
    public void testIsWrapperFor() throws SQLException {
        when(mockStatement.isWrapperFor(String.class)).thenReturn(true);

        boolean result = statementProxyXA.isWrapperFor(String.class);

        assertTrue(result);
        verify(mockStatement).isWrapperFor(String.class);
    }
}
