server:
  port: 9098

logging:
  config: classpath:logback.xml
  file:
    path: ${user.home}/logs

seata:
  config:
    type: file
    file:
      name: file.conf
    apollo:
      appId: seata-server
      apolloMeta: http://localhost:8801
      namespace: application
    nacos:
      serverAddr: 127.0.0.1:8848
      namespace:
      group: SEATA_GROUP
      username:
      password:
    consul:
      serverAddr: 127.0.0.1:8500
    zk:
      serverAddr: 127.0.0.1:2181
      sessionTimeout: 6000
      connectTimeout: 2000
      username:
      password:
    etcd3:
      serverAddr: http://localhost:2379
  registry:
    type: file
    file:
      name: file.conf
    zk:
      cluster: default
      serverAddr: 127.0.0.1:2181
      sessionTimeout: 6000
      connectTimeout: 2000
      username: ""
      password: ""
    nacos:
      application:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      cluster: default
      username:
      password:
    eureka:
      serviceUrl: http://localhost:8761/eureka
      application: default
      weight: 1
    redis:
      serverAddr: localhost:6379
      db: 0
      password:
      cluster: default
      timeout: 0
    consul:
      cluster: default
      serverAddr: 127.0.0.1:8500
    etcd3:
      cluster: default
      serverAddr: http://localhost:2379
    sofa:
      serverAddr: 127.0.0.1:9603
      application: default
      region: DEFAULT_ZONE
      datacenter: DefaultDataCenter
      cluster: default
      group: SEATA_GROUP
      addressWaitTime: 3000

  server:
    maxCommitRetryTimeout: -1
    maxRollbackRetryTimeout: -1
    rollbackRetryTimeoutUnlockEnable: false
    recovery:
      rollbackingRetryPeriod: 1000
      timeoutRetryPeriod: 1000
    undo:
      logSaveDays: 7
      logDeletePeriod: 86400000
  store:
    mode: file
    file:
      dir: sessionStore
      maxBranchSessionSize: 16384
      maxGlobalSessionSize: 512
      fileWriteBufferCacheSize: 16384
      flushDiskMode: async
      sessionReloadReadSize: 100
    db:
      datasource: druid
      dbType: mysql
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/seata?rewriteBatchedStatements=true
      user: root
      password: root
      minConn: 5
      maxConn: 30
      globalTable: global_table
      branchTable: branch_table
      lockTable: lock_table
      queryLimit: 100
      maxWait: 5000
    redis:
      mode: single
      maxConn: 10
      minConn: 1
      database: 0
      password: null
      queryLimit:
      sigle:
        host: 127.0.0.1
        port: 6379
      sentinel:
        masterName:
        sentinelHosts:
  metrics:
    enabled: false
    registryType: compact
    exporterList: prometheus
    exporterPrometheusPort: 9898


    



