// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: abstractResultMessage.proto

package io.seata.core.protocol.protobuf;

public interface AbstractResultMessageProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.seata.protocol.protobuf.AbstractResultMessageProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.seata.protocol.protobuf.AbstractMessageProto AbstractMessage = 1;</code>
   */
  boolean hasAbstractMessage();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractMessageProto AbstractMessage = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractMessageProto getAbstractMessage();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractMessageProto AbstractMessage = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractMessageProtoOrBuilder getAbstractMessageOrBuilder();

  /**
   * <code>.io.seata.protocol.protobuf.ResultCodeProto resultCode = 2;</code>
   */
  int getResultCodeValue();
  /**
   * <code>.io.seata.protocol.protobuf.ResultCodeProto resultCode = 2;</code>
   */
  io.seata.core.protocol.protobuf.ResultCodeProto getResultCode();

  /**
   * <code>string msg = 3;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 3;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
