// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: abstractTransactionRequest.proto

package io.seata.core.protocol.protobuf;

public interface AbstractTransactionRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.seata.protocol.protobuf.AbstractTransactionRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.seata.protocol.protobuf.AbstractMessageProto abstractMessage = 1;</code>
   */
  boolean hasAbstractMessage();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractMessageProto abstractMessage = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractMessageProto getAbstractMessage();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractMessageProto abstractMessage = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractMessageProtoOrBuilder getAbstractMessageOrBuilder();
}
