// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: branchCommitRequest.proto

package io.seata.core.protocol.protobuf;

public interface BranchCommitRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.seata.protocol.protobuf.BranchCommitRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.seata.protocol.protobuf.AbstractBranchEndRequestProto abstractBranchEndRequest = 1;</code>
   */
  boolean hasAbstractBranchEndRequest();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractBranchEndRequestProto abstractBranchEndRequest = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractBranchEndRequestProto getAbstractBranchEndRequest();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractBranchEndRequestProto abstractBranchEndRequest = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractBranchEndRequestProtoOrBuilder getAbstractBranchEndRequestOrBuilder();
}
