// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: branchReportResponse.proto

package io.seata.core.protocol.protobuf;

public final class BranchReportResponse {
  private BranchReportResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_seata_protocol_protobuf_BranchReportResponseProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_seata_protocol_protobuf_BranchReportResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032branchReportResponse.proto\022\032io.seata.p" +
      "rotocol.protobuf\032!abstractTransactionRes" +
      "ponse.proto\"~\n\031BranchReportResponseProto" +
      "\022a\n\033abstractTransactionResponse\030\001 \001(\0132<." +
      "io.seata.protocol.protobuf.AbstractTrans" +
      "actionResponseProtoB9\n\037io.seata.core.pro" +
      "tocol.protobufB\024BranchReportResponseP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.seata.core.protocol.protobuf.AbstractTransactionResponse.getDescriptor(),
        }, assigner);
    internal_static_io_seata_protocol_protobuf_BranchReportResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_seata_protocol_protobuf_BranchReportResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_seata_protocol_protobuf_BranchReportResponseProto_descriptor,
        new java.lang.String[] { "AbstractTransactionResponse", });
    io.seata.core.protocol.protobuf.AbstractTransactionResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
