// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: branchRollbackResponse.proto

package io.seata.core.protocol.protobuf;

public interface BranchRollbackResponseProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.seata.protocol.protobuf.BranchRollbackResponseProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.seata.protocol.protobuf.AbstractBranchEndResponseProto abstractBranchEndResponse = 1;</code>
   */
  boolean hasAbstractBranchEndResponse();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractBranchEndResponseProto abstractBranchEndResponse = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractBranchEndResponseProto getAbstractBranchEndResponse();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractBranchEndResponseProto abstractBranchEndResponse = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractBranchEndResponseProtoOrBuilder getAbstractBranchEndResponseOrBuilder();
}
