// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: globalStatusResponse.proto

package io.seata.core.protocol.protobuf;

public interface GlobalStatusResponseProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.seata.protocol.protobuf.GlobalStatusResponseProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.seata.protocol.protobuf.AbstractGlobalEndResponseProto abstractGlobalEndResponse = 1;</code>
   */
  boolean hasAbstractGlobalEndResponse();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractGlobalEndResponseProto abstractGlobalEndResponse = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractGlobalEndResponseProto getAbstractGlobalEndResponse();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractGlobalEndResponseProto abstractGlobalEndResponse = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractGlobalEndResponseProtoOrBuilder getAbstractGlobalEndResponseOrBuilder();
}
