// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: globalLockQueryRequest.proto

package io.seata.core.protocol.protobuf;

public interface GlobalLockQueryRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.seata.protocol.protobuf.GlobalLockQueryRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.seata.protocol.protobuf.BranchRegisterRequestProto branchRegisterRequest = 1;</code>
   */
  boolean hasBranchRegisterRequest();
  /**
   * <code>.io.seata.protocol.protobuf.BranchRegisterRequestProto branchRegisterRequest = 1;</code>
   */
  io.seata.core.protocol.protobuf.BranchRegisterRequestProto getBranchRegisterRequest();
  /**
   * <code>.io.seata.protocol.protobuf.BranchRegisterRequestProto branchRegisterRequest = 1;</code>
   */
  io.seata.core.protocol.protobuf.BranchRegisterRequestProtoOrBuilder getBranchRegisterRequestOrBuilder();
}
