// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: globalRollbackResponse.proto

package io.seata.core.protocol.protobuf;

public interface GlobalRollbackResponseProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.seata.protocol.protobuf.GlobalRollbackResponseProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.seata.protocol.protobuf.AbstractGlobalEndResponseProto abstractGlobalEndResponse = 1;</code>
   */
  boolean hasAbstractGlobalEndResponse();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractGlobalEndResponseProto abstractGlobalEndResponse = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractGlobalEndResponseProto getAbstractGlobalEndResponse();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractGlobalEndResponseProto abstractGlobalEndResponse = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractGlobalEndResponseProtoOrBuilder getAbstractGlobalEndResponseOrBuilder();
}
