// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: globalRollbackRequest.proto

package io.seata.core.protocol.protobuf;

/**
 * Protobuf type {@code io.seata.protocol.protobuf.GlobalRollbackRequestProto}
 */
public  final class GlobalRollbackRequestProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.seata.protocol.protobuf.GlobalRollbackRequestProto)
    GlobalRollbackRequestProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GlobalRollbackRequestProto.newBuilder() to construct.
  private GlobalRollbackRequestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GlobalRollbackRequestProto() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GlobalRollbackRequestProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto.Builder subBuilder = null;
            if (abstractGlobalEndRequest_ != null) {
              subBuilder = abstractGlobalEndRequest_.toBuilder();
            }
            abstractGlobalEndRequest_ = input.readMessage(io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(abstractGlobalEndRequest_);
              abstractGlobalEndRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.seata.core.protocol.protobuf.GlobalRollbackRequest.internal_static_io_seata_protocol_protobuf_GlobalRollbackRequestProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.seata.core.protocol.protobuf.GlobalRollbackRequest.internal_static_io_seata_protocol_protobuf_GlobalRollbackRequestProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.seata.core.protocol.protobuf.GlobalRollbackRequestProto.class, io.seata.core.protocol.protobuf.GlobalRollbackRequestProto.Builder.class);
  }

  public static final int ABSTRACTGLOBALENDREQUEST_FIELD_NUMBER = 1;
  private io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest_;
  /**
   * <code>.io.seata.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest = 1;</code>
   */
  public boolean hasAbstractGlobalEndRequest() {
    return abstractGlobalEndRequest_ != null;
  }
  /**
   * <code>.io.seata.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest = 1;</code>
   */
  public io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto getAbstractGlobalEndRequest() {
    return abstractGlobalEndRequest_ == null ? io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto.getDefaultInstance() : abstractGlobalEndRequest_;
  }
  /**
   * <code>.io.seata.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest = 1;</code>
   */
  public io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProtoOrBuilder getAbstractGlobalEndRequestOrBuilder() {
    return getAbstractGlobalEndRequest();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (abstractGlobalEndRequest_ != null) {
      output.writeMessage(1, getAbstractGlobalEndRequest());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (abstractGlobalEndRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAbstractGlobalEndRequest());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.seata.core.protocol.protobuf.GlobalRollbackRequestProto)) {
      return super.equals(obj);
    }
    io.seata.core.protocol.protobuf.GlobalRollbackRequestProto other = (io.seata.core.protocol.protobuf.GlobalRollbackRequestProto) obj;

    if (hasAbstractGlobalEndRequest() != other.hasAbstractGlobalEndRequest()) return false;
    if (hasAbstractGlobalEndRequest()) {
      if (!getAbstractGlobalEndRequest()
          .equals(other.getAbstractGlobalEndRequest())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAbstractGlobalEndRequest()) {
      hash = (37 * hash) + ABSTRACTGLOBALENDREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getAbstractGlobalEndRequest().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.seata.core.protocol.protobuf.GlobalRollbackRequestProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.seata.core.protocol.protobuf.GlobalRollbackRequestProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.seata.core.protocol.protobuf.GlobalRollbackRequestProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.seata.core.protocol.protobuf.GlobalRollbackRequestProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.seata.core.protocol.protobuf.GlobalRollbackRequestProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.seata.core.protocol.protobuf.GlobalRollbackRequestProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.seata.core.protocol.protobuf.GlobalRollbackRequestProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.seata.core.protocol.protobuf.GlobalRollbackRequestProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.seata.core.protocol.protobuf.GlobalRollbackRequestProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.seata.core.protocol.protobuf.GlobalRollbackRequestProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.seata.core.protocol.protobuf.GlobalRollbackRequestProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.seata.core.protocol.protobuf.GlobalRollbackRequestProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.seata.core.protocol.protobuf.GlobalRollbackRequestProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.seata.protocol.protobuf.GlobalRollbackRequestProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.seata.protocol.protobuf.GlobalRollbackRequestProto)
      io.seata.core.protocol.protobuf.GlobalRollbackRequestProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.seata.core.protocol.protobuf.GlobalRollbackRequest.internal_static_io_seata_protocol_protobuf_GlobalRollbackRequestProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.seata.core.protocol.protobuf.GlobalRollbackRequest.internal_static_io_seata_protocol_protobuf_GlobalRollbackRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.seata.core.protocol.protobuf.GlobalRollbackRequestProto.class, io.seata.core.protocol.protobuf.GlobalRollbackRequestProto.Builder.class);
    }

    // Construct using io.seata.core.protocol.protobuf.GlobalRollbackRequestProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (abstractGlobalEndRequestBuilder_ == null) {
        abstractGlobalEndRequest_ = null;
      } else {
        abstractGlobalEndRequest_ = null;
        abstractGlobalEndRequestBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.seata.core.protocol.protobuf.GlobalRollbackRequest.internal_static_io_seata_protocol_protobuf_GlobalRollbackRequestProto_descriptor;
    }

    @java.lang.Override
    public io.seata.core.protocol.protobuf.GlobalRollbackRequestProto getDefaultInstanceForType() {
      return io.seata.core.protocol.protobuf.GlobalRollbackRequestProto.getDefaultInstance();
    }

    @java.lang.Override
    public io.seata.core.protocol.protobuf.GlobalRollbackRequestProto build() {
      io.seata.core.protocol.protobuf.GlobalRollbackRequestProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.seata.core.protocol.protobuf.GlobalRollbackRequestProto buildPartial() {
      io.seata.core.protocol.protobuf.GlobalRollbackRequestProto result = new io.seata.core.protocol.protobuf.GlobalRollbackRequestProto(this);
      if (abstractGlobalEndRequestBuilder_ == null) {
        result.abstractGlobalEndRequest_ = abstractGlobalEndRequest_;
      } else {
        result.abstractGlobalEndRequest_ = abstractGlobalEndRequestBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.seata.core.protocol.protobuf.GlobalRollbackRequestProto) {
        return mergeFrom((io.seata.core.protocol.protobuf.GlobalRollbackRequestProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.seata.core.protocol.protobuf.GlobalRollbackRequestProto other) {
      if (other == io.seata.core.protocol.protobuf.GlobalRollbackRequestProto.getDefaultInstance()) return this;
      if (other.hasAbstractGlobalEndRequest()) {
        mergeAbstractGlobalEndRequest(other.getAbstractGlobalEndRequest());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.seata.core.protocol.protobuf.GlobalRollbackRequestProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.seata.core.protocol.protobuf.GlobalRollbackRequestProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto, io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto.Builder, io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProtoOrBuilder> abstractGlobalEndRequestBuilder_;
    /**
     * <code>.io.seata.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest = 1;</code>
     */
    public boolean hasAbstractGlobalEndRequest() {
      return abstractGlobalEndRequestBuilder_ != null || abstractGlobalEndRequest_ != null;
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest = 1;</code>
     */
    public io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto getAbstractGlobalEndRequest() {
      if (abstractGlobalEndRequestBuilder_ == null) {
        return abstractGlobalEndRequest_ == null ? io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto.getDefaultInstance() : abstractGlobalEndRequest_;
      } else {
        return abstractGlobalEndRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest = 1;</code>
     */
    public Builder setAbstractGlobalEndRequest(io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto value) {
      if (abstractGlobalEndRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        abstractGlobalEndRequest_ = value;
        onChanged();
      } else {
        abstractGlobalEndRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest = 1;</code>
     */
    public Builder setAbstractGlobalEndRequest(
        io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto.Builder builderForValue) {
      if (abstractGlobalEndRequestBuilder_ == null) {
        abstractGlobalEndRequest_ = builderForValue.build();
        onChanged();
      } else {
        abstractGlobalEndRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest = 1;</code>
     */
    public Builder mergeAbstractGlobalEndRequest(io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto value) {
      if (abstractGlobalEndRequestBuilder_ == null) {
        if (abstractGlobalEndRequest_ != null) {
          abstractGlobalEndRequest_ =
            io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto.newBuilder(abstractGlobalEndRequest_).mergeFrom(value).buildPartial();
        } else {
          abstractGlobalEndRequest_ = value;
        }
        onChanged();
      } else {
        abstractGlobalEndRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest = 1;</code>
     */
    public Builder clearAbstractGlobalEndRequest() {
      if (abstractGlobalEndRequestBuilder_ == null) {
        abstractGlobalEndRequest_ = null;
        onChanged();
      } else {
        abstractGlobalEndRequest_ = null;
        abstractGlobalEndRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest = 1;</code>
     */
    public io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto.Builder getAbstractGlobalEndRequestBuilder() {
      
      onChanged();
      return getAbstractGlobalEndRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest = 1;</code>
     */
    public io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProtoOrBuilder getAbstractGlobalEndRequestOrBuilder() {
      if (abstractGlobalEndRequestBuilder_ != null) {
        return abstractGlobalEndRequestBuilder_.getMessageOrBuilder();
      } else {
        return abstractGlobalEndRequest_ == null ?
            io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto.getDefaultInstance() : abstractGlobalEndRequest_;
      }
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto, io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto.Builder, io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProtoOrBuilder> 
        getAbstractGlobalEndRequestFieldBuilder() {
      if (abstractGlobalEndRequestBuilder_ == null) {
        abstractGlobalEndRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto, io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto.Builder, io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProtoOrBuilder>(
                getAbstractGlobalEndRequest(),
                getParentForChildren(),
                isClean());
        abstractGlobalEndRequest_ = null;
      }
      return abstractGlobalEndRequestBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.seata.protocol.protobuf.GlobalRollbackRequestProto)
  }

  // @@protoc_insertion_point(class_scope:io.seata.protocol.protobuf.GlobalRollbackRequestProto)
  private static final io.seata.core.protocol.protobuf.GlobalRollbackRequestProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.seata.core.protocol.protobuf.GlobalRollbackRequestProto();
  }

  public static io.seata.core.protocol.protobuf.GlobalRollbackRequestProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GlobalRollbackRequestProto>
      PARSER = new com.google.protobuf.AbstractParser<GlobalRollbackRequestProto>() {
    @java.lang.Override
    public GlobalRollbackRequestProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GlobalRollbackRequestProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GlobalRollbackRequestProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GlobalRollbackRequestProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.seata.core.protocol.protobuf.GlobalRollbackRequestProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

