// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: globalStatusRequest.proto

package io.seata.core.protocol.protobuf;

public interface GlobalStatusRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.seata.protocol.protobuf.GlobalStatusRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.seata.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest = 1;</code>
   */
  boolean hasAbstractGlobalEndRequest();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProto getAbstractGlobalEndRequest();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractGlobalEndRequestProto abstractGlobalEndRequest = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractGlobalEndRequestProtoOrBuilder getAbstractGlobalEndRequestOrBuilder();
}
