// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeatMessage.proto

package io.seata.core.protocol.protobuf;

public interface HeartbeatMessageProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.seata.protocol.protobuf.HeartbeatMessageProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool pingOrPong = 1;</code>
   */
  boolean getPingOrPong();
}
