// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mergedResultMessage.proto

package io.seata.core.protocol.protobuf;

public interface MergedResultMessageProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.seata.protocol.protobuf.MergedResultMessageProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.seata.protocol.protobuf.AbstractMessageProto abstractMessage = 1;</code>
   */
  boolean hasAbstractMessage();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractMessageProto abstractMessage = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractMessageProto getAbstractMessage();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractMessageProto abstractMessage = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractMessageProtoOrBuilder getAbstractMessageOrBuilder();

  /**
   * <code>repeated .google.protobuf.Any msgs = 2;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getMsgsList();
  /**
   * <code>repeated .google.protobuf.Any msgs = 2;</code>
   */
  com.google.protobuf.Any getMsgs(int index);
  /**
   * <code>repeated .google.protobuf.Any msgs = 2;</code>
   */
  int getMsgsCount();
  /**
   * <code>repeated .google.protobuf.Any msgs = 2;</code>
   */
  java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getMsgsOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Any msgs = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getMsgsOrBuilder(
      int index);

  /**
   * <code>repeated string msgIds = 3;</code>
   */
  java.util.List<java.lang.String>
      getMsgIdsList();
  /**
   * <code>repeated string msgIds = 3;</code>
   */
  int getMsgIdsCount();
  /**
   * <code>repeated string msgIds = 3;</code>
   */
  java.lang.String getMsgIds(int index);
  /**
   * <code>repeated string msgIds = 3;</code>
   */
  com.google.protobuf.ByteString
      getMsgIdsBytes(int index);
}
