// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mergedWarpMessage.proto

package io.seata.core.protocol.protobuf;

public final class MergedWarpMessage {
  private MergedWarpMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_seata_protocol_protobuf_MergedWarpMessageProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_seata_protocol_protobuf_MergedWarpMessageProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027mergedWarpMessage.proto\022\032io.seata.prot" +
      "ocol.protobuf\032\025abstractMessage.proto\032\031go" +
      "ogle/protobuf/any.proto\"\207\001\n\026MergedWarpMe" +
      "ssageProto\022I\n\017abstractMessage\030\001 \001(\01320.io" +
      ".seata.protocol.protobuf.AbstractMessage" +
      "Proto\022\"\n\004msgs\030\002 \003(\0132\024.google.protobuf.An" +
      "yB6\n\037io.seata.core.protocol.protobufB\021Me" +
      "rgedWarpMessageP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.seata.core.protocol.protobuf.AbstractMessage.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_io_seata_protocol_protobuf_MergedWarpMessageProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_seata_protocol_protobuf_MergedWarpMessageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_seata_protocol_protobuf_MergedWarpMessageProto_descriptor,
        new java.lang.String[] { "AbstractMessage", "Msgs", });
    io.seata.core.protocol.protobuf.AbstractMessage.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
