// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registerTMRequest.proto

package io.seata.core.protocol.protobuf;

public interface RegisterTMRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.seata.protocol.protobuf.RegisterTMRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.seata.protocol.protobuf.AbstractIdentifyRequestProto abstractIdentifyRequest = 1;</code>
   */
  boolean hasAbstractIdentifyRequest();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractIdentifyRequestProto abstractIdentifyRequest = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractIdentifyRequestProto getAbstractIdentifyRequest();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractIdentifyRequestProto abstractIdentifyRequest = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractIdentifyRequestProtoOrBuilder getAbstractIdentifyRequestOrBuilder();
}
