// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registerRMResponse.proto

package io.seata.core.protocol.protobuf;

public interface RegisterRMResponseProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.seata.protocol.protobuf.RegisterRMResponseProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.seata.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse = 1;</code>
   */
  boolean hasAbstractIdentifyResponse();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto getAbstractIdentifyResponse();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractIdentifyResponseProtoOrBuilder getAbstractIdentifyResponseOrBuilder();
}
