// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registerRMResponse.proto

package io.seata.core.protocol.protobuf;

/**
 * <pre>
 * PublishRequest is a publish request.
 * </pre>
 *
 * Protobuf type {@code io.seata.protocol.protobuf.RegisterRMResponseProto}
 */
public  final class RegisterRMResponseProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.seata.protocol.protobuf.RegisterRMResponseProto)
    RegisterRMResponseProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RegisterRMResponseProto.newBuilder() to construct.
  private RegisterRMResponseProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RegisterRMResponseProto() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RegisterRMResponseProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto.Builder subBuilder = null;
            if (abstractIdentifyResponse_ != null) {
              subBuilder = abstractIdentifyResponse_.toBuilder();
            }
            abstractIdentifyResponse_ = input.readMessage(io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(abstractIdentifyResponse_);
              abstractIdentifyResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.seata.core.protocol.protobuf.RegisterRMResponse.internal_static_io_seata_protocol_protobuf_RegisterRMResponseProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.seata.core.protocol.protobuf.RegisterRMResponse.internal_static_io_seata_protocol_protobuf_RegisterRMResponseProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.seata.core.protocol.protobuf.RegisterRMResponseProto.class, io.seata.core.protocol.protobuf.RegisterRMResponseProto.Builder.class);
  }

  public static final int ABSTRACTIDENTIFYRESPONSE_FIELD_NUMBER = 1;
  private io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse_;
  /**
   * <code>.io.seata.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse = 1;</code>
   */
  public boolean hasAbstractIdentifyResponse() {
    return abstractIdentifyResponse_ != null;
  }
  /**
   * <code>.io.seata.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse = 1;</code>
   */
  public io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto getAbstractIdentifyResponse() {
    return abstractIdentifyResponse_ == null ? io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto.getDefaultInstance() : abstractIdentifyResponse_;
  }
  /**
   * <code>.io.seata.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse = 1;</code>
   */
  public io.seata.core.protocol.protobuf.AbstractIdentifyResponseProtoOrBuilder getAbstractIdentifyResponseOrBuilder() {
    return getAbstractIdentifyResponse();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (abstractIdentifyResponse_ != null) {
      output.writeMessage(1, getAbstractIdentifyResponse());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (abstractIdentifyResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAbstractIdentifyResponse());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.seata.core.protocol.protobuf.RegisterRMResponseProto)) {
      return super.equals(obj);
    }
    io.seata.core.protocol.protobuf.RegisterRMResponseProto other = (io.seata.core.protocol.protobuf.RegisterRMResponseProto) obj;

    if (hasAbstractIdentifyResponse() != other.hasAbstractIdentifyResponse()) return false;
    if (hasAbstractIdentifyResponse()) {
      if (!getAbstractIdentifyResponse()
          .equals(other.getAbstractIdentifyResponse())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAbstractIdentifyResponse()) {
      hash = (37 * hash) + ABSTRACTIDENTIFYRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getAbstractIdentifyResponse().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.seata.core.protocol.protobuf.RegisterRMResponseProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.seata.core.protocol.protobuf.RegisterRMResponseProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.seata.core.protocol.protobuf.RegisterRMResponseProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.seata.core.protocol.protobuf.RegisterRMResponseProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.seata.core.protocol.protobuf.RegisterRMResponseProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.seata.core.protocol.protobuf.RegisterRMResponseProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.seata.core.protocol.protobuf.RegisterRMResponseProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.seata.core.protocol.protobuf.RegisterRMResponseProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.seata.core.protocol.protobuf.RegisterRMResponseProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.seata.core.protocol.protobuf.RegisterRMResponseProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.seata.core.protocol.protobuf.RegisterRMResponseProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.seata.core.protocol.protobuf.RegisterRMResponseProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.seata.core.protocol.protobuf.RegisterRMResponseProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * PublishRequest is a publish request.
   * </pre>
   *
   * Protobuf type {@code io.seata.protocol.protobuf.RegisterRMResponseProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.seata.protocol.protobuf.RegisterRMResponseProto)
      io.seata.core.protocol.protobuf.RegisterRMResponseProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.seata.core.protocol.protobuf.RegisterRMResponse.internal_static_io_seata_protocol_protobuf_RegisterRMResponseProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.seata.core.protocol.protobuf.RegisterRMResponse.internal_static_io_seata_protocol_protobuf_RegisterRMResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.seata.core.protocol.protobuf.RegisterRMResponseProto.class, io.seata.core.protocol.protobuf.RegisterRMResponseProto.Builder.class);
    }

    // Construct using io.seata.core.protocol.protobuf.RegisterRMResponseProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (abstractIdentifyResponseBuilder_ == null) {
        abstractIdentifyResponse_ = null;
      } else {
        abstractIdentifyResponse_ = null;
        abstractIdentifyResponseBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.seata.core.protocol.protobuf.RegisterRMResponse.internal_static_io_seata_protocol_protobuf_RegisterRMResponseProto_descriptor;
    }

    @java.lang.Override
    public io.seata.core.protocol.protobuf.RegisterRMResponseProto getDefaultInstanceForType() {
      return io.seata.core.protocol.protobuf.RegisterRMResponseProto.getDefaultInstance();
    }

    @java.lang.Override
    public io.seata.core.protocol.protobuf.RegisterRMResponseProto build() {
      io.seata.core.protocol.protobuf.RegisterRMResponseProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.seata.core.protocol.protobuf.RegisterRMResponseProto buildPartial() {
      io.seata.core.protocol.protobuf.RegisterRMResponseProto result = new io.seata.core.protocol.protobuf.RegisterRMResponseProto(this);
      if (abstractIdentifyResponseBuilder_ == null) {
        result.abstractIdentifyResponse_ = abstractIdentifyResponse_;
      } else {
        result.abstractIdentifyResponse_ = abstractIdentifyResponseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.seata.core.protocol.protobuf.RegisterRMResponseProto) {
        return mergeFrom((io.seata.core.protocol.protobuf.RegisterRMResponseProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.seata.core.protocol.protobuf.RegisterRMResponseProto other) {
      if (other == io.seata.core.protocol.protobuf.RegisterRMResponseProto.getDefaultInstance()) return this;
      if (other.hasAbstractIdentifyResponse()) {
        mergeAbstractIdentifyResponse(other.getAbstractIdentifyResponse());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.seata.core.protocol.protobuf.RegisterRMResponseProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.seata.core.protocol.protobuf.RegisterRMResponseProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto, io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto.Builder, io.seata.core.protocol.protobuf.AbstractIdentifyResponseProtoOrBuilder> abstractIdentifyResponseBuilder_;
    /**
     * <code>.io.seata.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse = 1;</code>
     */
    public boolean hasAbstractIdentifyResponse() {
      return abstractIdentifyResponseBuilder_ != null || abstractIdentifyResponse_ != null;
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse = 1;</code>
     */
    public io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto getAbstractIdentifyResponse() {
      if (abstractIdentifyResponseBuilder_ == null) {
        return abstractIdentifyResponse_ == null ? io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto.getDefaultInstance() : abstractIdentifyResponse_;
      } else {
        return abstractIdentifyResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse = 1;</code>
     */
    public Builder setAbstractIdentifyResponse(io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto value) {
      if (abstractIdentifyResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        abstractIdentifyResponse_ = value;
        onChanged();
      } else {
        abstractIdentifyResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse = 1;</code>
     */
    public Builder setAbstractIdentifyResponse(
        io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto.Builder builderForValue) {
      if (abstractIdentifyResponseBuilder_ == null) {
        abstractIdentifyResponse_ = builderForValue.build();
        onChanged();
      } else {
        abstractIdentifyResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse = 1;</code>
     */
    public Builder mergeAbstractIdentifyResponse(io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto value) {
      if (abstractIdentifyResponseBuilder_ == null) {
        if (abstractIdentifyResponse_ != null) {
          abstractIdentifyResponse_ =
            io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto.newBuilder(abstractIdentifyResponse_).mergeFrom(value).buildPartial();
        } else {
          abstractIdentifyResponse_ = value;
        }
        onChanged();
      } else {
        abstractIdentifyResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse = 1;</code>
     */
    public Builder clearAbstractIdentifyResponse() {
      if (abstractIdentifyResponseBuilder_ == null) {
        abstractIdentifyResponse_ = null;
        onChanged();
      } else {
        abstractIdentifyResponse_ = null;
        abstractIdentifyResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse = 1;</code>
     */
    public io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto.Builder getAbstractIdentifyResponseBuilder() {
      
      onChanged();
      return getAbstractIdentifyResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse = 1;</code>
     */
    public io.seata.core.protocol.protobuf.AbstractIdentifyResponseProtoOrBuilder getAbstractIdentifyResponseOrBuilder() {
      if (abstractIdentifyResponseBuilder_ != null) {
        return abstractIdentifyResponseBuilder_.getMessageOrBuilder();
      } else {
        return abstractIdentifyResponse_ == null ?
            io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto.getDefaultInstance() : abstractIdentifyResponse_;
      }
    }
    /**
     * <code>.io.seata.protocol.protobuf.AbstractIdentifyResponseProto abstractIdentifyResponse = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto, io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto.Builder, io.seata.core.protocol.protobuf.AbstractIdentifyResponseProtoOrBuilder> 
        getAbstractIdentifyResponseFieldBuilder() {
      if (abstractIdentifyResponseBuilder_ == null) {
        abstractIdentifyResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto, io.seata.core.protocol.protobuf.AbstractIdentifyResponseProto.Builder, io.seata.core.protocol.protobuf.AbstractIdentifyResponseProtoOrBuilder>(
                getAbstractIdentifyResponse(),
                getParentForChildren(),
                isClean());
        abstractIdentifyResponse_ = null;
      }
      return abstractIdentifyResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.seata.protocol.protobuf.RegisterRMResponseProto)
  }

  // @@protoc_insertion_point(class_scope:io.seata.protocol.protobuf.RegisterRMResponseProto)
  private static final io.seata.core.protocol.protobuf.RegisterRMResponseProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.seata.core.protocol.protobuf.RegisterRMResponseProto();
  }

  public static io.seata.core.protocol.protobuf.RegisterRMResponseProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegisterRMResponseProto>
      PARSER = new com.google.protobuf.AbstractParser<RegisterRMResponseProto>() {
    @java.lang.Override
    public RegisterRMResponseProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RegisterRMResponseProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RegisterRMResponseProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegisterRMResponseProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.seata.core.protocol.protobuf.RegisterRMResponseProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

