// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registerRMRequest.proto

package io.seata.core.protocol.protobuf;

public interface RegisterRMRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.seata.protocol.protobuf.RegisterRMRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.seata.protocol.protobuf.AbstractIdentifyRequestProto abstractIdentifyRequest = 1;</code>
   */
  boolean hasAbstractIdentifyRequest();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractIdentifyRequestProto abstractIdentifyRequest = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractIdentifyRequestProto getAbstractIdentifyRequest();
  /**
   * <code>.io.seata.protocol.protobuf.AbstractIdentifyRequestProto abstractIdentifyRequest = 1;</code>
   */
  io.seata.core.protocol.protobuf.AbstractIdentifyRequestProtoOrBuilder getAbstractIdentifyRequestOrBuilder();

  /**
   * <code>string resourceIds = 2;</code>
   */
  java.lang.String getResourceIds();
  /**
   * <code>string resourceIds = 2;</code>
   */
  com.google.protobuf.ByteString
      getResourceIdsBytes();
}
