// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registerRMResponse.proto

package io.seata.core.protocol.protobuf;

public final class RegisterRMResponse {
  private RegisterRMResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_seata_protocol_protobuf_RegisterRMResponseProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_seata_protocol_protobuf_RegisterRMResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030registerRMResponse.proto\022\032io.seata.pro" +
      "tocol.protobuf\032\036abstractIdentifyResponse" +
      ".proto\"\213\001\n\027RegisterRMResponseProto\022[\n\030ab" +
      "stractIdentifyResponse\030\001 \001(\01329.io.seata." +
      "protocol.protobuf.AbstractIdentifyRespon" +
      "seProto\022\023\n\013resourceIds\030\002 \001(\tB7\n\037io.seata" +
      ".core.protocol.protobufB\022RegisterRMRespo" +
      "nseP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.seata.core.protocol.protobuf.AbstractIdentifyResponse.getDescriptor(),
        }, assigner);
    internal_static_io_seata_protocol_protobuf_RegisterRMResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_seata_protocol_protobuf_RegisterRMResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_seata_protocol_protobuf_RegisterRMResponseProto_descriptor,
        new java.lang.String[] { "AbstractIdentifyResponse", "ResourceIds", });
    io.seata.core.protocol.protobuf.AbstractIdentifyResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
