{
 "title": "Seata业务大盘",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(seata_transaction,kubeone_ali_appinstance_name)"
   },
   {
    "name": "group",
    "label": "group",
    "query": "label_values(seata_transaction,group)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(seata_transaction {kubeone_ali_appinstance_name=\"$instance\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "事务总量统计",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(seata_transaction{kubeone_ali_appinstance_name=\"$instance\",group=~\"$group\",meter=\"counter\",pod=\"$pod\"}) by  (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "事务耗时(含业务时间)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(seata_transaction{kubeone_ali_appinstance_name=\"$instance\",group=~\"$group\",meter=\"timer\",statistic=\"average\",pod=\"$pod\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "正常事务统计",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(seata_transaction{kubeone_ali_appinstance_name=\"$instance\",group=~\"$group\",meter=\"summary\",statistic=\"count\",status=~\"committed|rollbacked\",pod=\"$pod\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "异常事务统计",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(seata_transaction{kubeone_ali_appinstance_name=\"$instance\",group=~\"$group\",meter=\"summary\",statistic=\"count\",status=~\"unretry|timeout\",pod=\"$pod\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "事务TPS(按状态)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(seata_transaction{kubeone_ali_appinstance_name=\"$instance\",group=~\"$group\",meter=\"summary\",statistic=\"tps\",pod=\"$pod\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "事务TPS(按容器)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(seata_transaction{kubeone_ali_appinstance_name=\"$instance\",group=~\"$group\",meter=\"counter\",pod=\"$pod\",status=~\"committed|rollbacked\"}[1m])) by (kubeone_ali_appinstance_name)",
     "legendFormat": "{{kubeone_ali_appinstance_name}}{{pod}}"
    }
   ]
  }
 ]
}