name: License checker

on:
  pull_request:
      branches: [ 2.x, develop, master ]

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      # step 1
      - name: Checkout
        uses: actions/checkout@v3
      # step 2
      - name: Check License Header
        uses: apache/skywalking-eyes/header@main
        with:
          log: info
          config: .licenserc.yaml
          mode: check
      # step 3
      - name: Check Dependencies' License
        uses: apache/skywalking-eyes/dependency@main
        with:
          log: info
          config: .licenserc.yaml
          mode: check