name: License checker

on:
  pull_request:
      branches: [ 2.x, develop, master ]

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      # step 1
      - name: Checkout
        uses: actions/checkout@v2.4.0
      # step 2
      - name: Check License Header
        uses: apache/skywalking-eyes/header@8fc52baabc14c86294d96034bcc194cfa7f76b05
        with:
          log: info
          config: .licenserc.yaml
          mode: check
      # step 3
      - name: Check Dependencies' License
        uses: apache/skywalking-eyes/dependency@8fc52baabc14c86294d96034bcc194cfa7f76b05
        with:
          log: info
          config: .licenserc.yaml
          mode: check