name: "Publish To OSSRH"

on:
  push:
    branches: [ develop, 1.*.*, 2.*.* ]
    #tags: [ "*" ]

jobs:
  publish:
    name: "Publish To OSSRH"
    runs-on: ubuntu-latest
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v2.4.0

      # step 2
      - name: "Setup Java JDK"
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: 8
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD

      # step 3
      - name: "Import GPG-SECRET-KEY"
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import

      # step 4
      - name: "Package and Publish-To-OSSRH"
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USER }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./mvnw -T 4C clean deploy -Prelease,release-by-github-actions -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} --batch-mode -e -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
