name: "Publish To OSSRH"

on:
  push:
    branches: [ develop, 1.*.*, 2.*.* ]
    #tags: [ * ]

  #在此PR中先校验一遍，成功后，再删掉
  pull_request:
    branches: [ develop ]

jobs:
  publish:
    name: "Publish"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
            #macos-latest,  # unsuccessful
            #ubuntu-latest, # unsuccessful
            windows-latest  # successful
        ]
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v2.4.0

      # step 2
      - name: "Setup Java JDK"
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: 8

      # step 3
      #- name: "Install GPG For MacOS"
      #  if: startsWith(matrix.os, 'macos')
      #  run: brew install gnupg

      # step 4
      - name: "Package and Publish-To-OSSRH"
        uses: samuelmeuli/action-maven-publish@v1.4.0
        with:
          nexus_username: ${{ secrets.OSSRH_USER }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          #Command Template: mvn ${mavenGoalsPhases} --batch-mode --activate-profiles ${mavenProfiles} --settings ${mavenSettingsPath} ${mavenArgs}
          #  see the source: https://github.com/samuelmeuli/action-maven-publish/blob/master/index.js#L84
          #The following configurations will be spliced into the command template above
          maven_goals_phases: -T 4C clean deploy -e -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          maven_profiles: release,release-by-github-actions
