# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: TCC dubbo e2e

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    services:
      zookeeper:
        image: zookeeper
        ports:
          - 2181:2181
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: seata
          MYSQL_ROOT_HOST: 3306
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean package -DskipTests=true -Dcheckstyle.skip=true -U
    - name: git pull seata-samples
      run: |
        cd /tmp
        git clone -b feature/it https://github.com/q294881866/seata-samples.git seata-samples
        cd seata-samples
        mvn clean package -pl seata-samples-jit --also-make install
        mvn clean package -pl tcc/dubbo-tcc-sample --also-make
    - name: test
      run: |
       cd /tmp/seata-samples
       nohup java -cp .:seata-samples-jit/target/lib/*:seata-samples-jit/target/seata-jit-server.jar io.seata.samples.jit.Main &
       sleep 1m
       nohup java -cp .:tcc/dubbo-tcc-sample/target/lib/*:tcc/dubbo-tcc-sample/target/dubbo-tcc-sample.jar io.seata.samples.tcc.dubbo.starter.TccProviderStarter &
       sleep 1m
       java -cp .:tcc/dubbo-tcc-sample/target/lib/*:tcc/dubbo-tcc-sample/target/dubbo-tcc-sample.jar io.seata.samples.tcc.dubbo.starter.TccConsumerStarter
       ls ~/logs/seata
    - name: Contains error.log
      run: bash -x ./check_error.sh
    - name: The job has failed
      if: failure()
      run: echo 'TCC model fail!'
