name: "test"

on:
  push:
    branches: [ test*, "*.*.*" ]

jobs:
  # job 1
  test:
    name: "test"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 17, 21 ]
        springboot: [
          2.7.18         -Dspring-framework.version=5.3.31,
          2.6.15         -Dspring-framework.version=5.3.27,
          2.5.15         -Dspring-framework.version=5.3.27,
          2.4.13         -Dspring-framework.version=5.3.13,
          2.3.12.RELEASE -Dspring-framework.version=5.2.15.RELEASE,
          2.2.13.RELEASE -Dspring-framework.version=5.2.12.RELEASE,
          #2.1.18.RELEASE,
          #2.0.9.RELEASE,
        ]
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v3
      # step 2
      - name: "Set up Java JDK"
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      # step 3
      - name: "Print maven version"
        run: ./mvnw -version
      # step 4
      - name: "Test with Maven and Java${{ matrix.java }}"
        # https://docs.github.com/cn/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        run: |
          ./mvnw -T 4C clean test \
                 -P args-for-client-test \
                 -Dspring-boot.version=${{ matrix.springboot }} \
                 -Dmaven.git-commit-id.skip=true \
                 -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;

  # job 2
  test-springboot3x:
    name: "test-springboot3.x"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21 ]
        springboot: [
          3.2.0  -Dspring-framework.version=6.1.1,
          3.1.6  -Dspring-framework.version=6.0.14,
          3.0.13 -Dspring-framework.version=6.0.14,
        ]
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v3
      # step 2
      - name: "Set up Java JDK"
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      # step 3
      - name: "Print maven version"
        run: ./mvnw -version
      # step 4
      - name: "Test with Maven and Java${{ matrix.java }}"
        run: |
          ./mvnw -T 4C clean test \
                 -P args-for-client-test \
                 -Dspring-boot.version=${{ matrix.springboot }} \
                 -Dmaven.git-commit-id.skip=true \
                 -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
