name: "test-command"

on:
  push:
    branches: [ test-os ]

jobs:
  test-command:
    name: "test-command"
    runs-on: ubuntu-latest
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v3
      # step 2
      - name: "Set up QEMU"
        id: qemu
        uses: docker/setup-qemu-action@v3
      # step 3.1
      - name: "Show arm64v8/ubuntu OS info"
        run: |
          docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
            arm64v8/ubuntu:20.04 \
            bash -exc 'uname -v && \
                       cat /etc/os-release && \
                       cat /etc/issue && \
                       cat /proc/meminfo && \
                       cat /proc/cpuinfo';
      # step 3.2
      - name: "Show OS info"
        run: |
          uname -v;
          cat /etc/os-release;
          cat /etc/issue;
          cat /proc/meminfo;
          cat /proc/cpuinfo;
