name: "test"

on:
  push:
    branches: [ test*, "*.*.*" ]

jobs:
  # job 1
  test:
    name: "test"
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 17, 21 ]
        os: [
          macos
        ]
        springboot: [
          2.7.18,
          2.6.15,
          2.5.15,
          2.4.13,
          2.3.12.RELEASE,
          2.2.13.RELEASE,
          #2.1.18.RELEASE,
          #2.0.9.RELEASE
        ]
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v3
      # step 2
      - name: "Set up Java JDK"
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      # step 3
      ## step 3.1: for Ubuntu and MacOS
      - name: "Test with Maven on '${{ matrix.os }}' OS"
        if: matrix.os != 'windows'
        run: |
          ./mvnw     -version;
          ./mvnw     -T 4C clean test \
                     -P args-for-client-test \
                     -Dspring-boot.version=${{ matrix.springboot }} \
                     -Dmaven.git-commit-id.skip=true \
                     -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
      ## step 3.2: for Windows
      - name: "Build with Maven on 'windows' OS (Skip tests)"
        if: matrix.os == 'windows'
        run: | # Skip tests, because too many errors in unit-test.
          ./mvnw.cmd -version;
          ./mvnw.cmd clean install -P args-for-client-test -DskipTests -D spring-boot.version=${{ matrix.springboot }} -D maven.git-commit-id.skip=true -e -B -D org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;

  # job 2
  test-springboot3x:
    name: "test-springboot3.x"
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21 ]
        os: [
          macos
        ]
        springboot: [
          3.2.0,
          3.1.6,
          3.0.13
        ]
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v3
      # step 2
      - name: "Set up Java JDK"
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      # step 3
      ## step 3.1: for Ubuntu and MacOS
      - name: "Test with Maven on '${{ matrix.os }}' OS"
        if: matrix.os != 'windows'
        run: |
          ./mvnw     -version;
          ./mvnw     -T 4C clean install \
                     -P args-for-client-test \
                     -Dspring-boot.version=${{ matrix.springboot }} \
                     -Dmaven.git-commit-id.skip=true \
                     -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
      ## step 3.2: for Windows
      - name: "Build with Maven on 'windows' OS (Skip tests)"
        if: matrix.os == 'windows'
        run: | # Skip tests, because too many errors in unit-test.
          ./mvnw.cmd -version;
          ./mvnw.cmd clean install -P args-for-client-test -DskipTests -D spring-boot.version=${{ matrix.springboot }} -D maven.git-commit-id.skip=true -e -B -D org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
