name: "test-os"

on:
  push:
    branches: [ test*, "*.*.*" ]

jobs:
  # job 1
  test-os:
    name: "test-os"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          #ubuntu-latest, # Already tested in `test.yml`
          macos-latest,
          windows-latest, # Skip tests, because too many errors in unit-test.
        ]
        java: [ 8, 11, 17, 21 ]
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v3
      # step 2
      - name: "Set up Java JDK"
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      # step 3
      ## step 3.1: for MacOS
      - name: "Test with Maven on 'macos-latest' OS"
        if: matrix.os == 'macos-latest'
        run: |
          ./mvnw     -version;
          ./mvnw     clean install \
                     -Dmaven.git-commit-id.skip=true \
                     -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
      ## step 3.2: for Windows
      - name: "Build with Maven on 'windows-latest' OS (Skip tests)"
        if: matrix.os == 'windows-latest'
        run: | # Skip tests, because too many errors in unit-test.
          ./mvnw.cmd -version;
          ./mvnw.cmd clean install -DskipTests -e -B;

  # job 2:
  test-arm64:
    name: "test-arm64"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        springboot: [
          #2.7.17         -Dspring-framework.version=5.3.30, # The maven-compiler-plugin will throw an error for an unknown reason.
          #2.6.15         -Dspring-framework.version=5.3.27, # The maven-compiler-plugin will throw an error for an unknown reason.
          #2.5.15         -Dspring-framework.version=5.3.27, # The maven-compiler-plugin will throw an error for an unknown reason.
          2.4.13         -Dspring-framework.version=5.3.13,
          2.3.12.RELEASE -Dspring-framework.version=5.2.15.RELEASE,
          2.2.13.RELEASE -Dspring-framework.version=5.2.12.RELEASE,
          #2.1.18.RELEASE,
          #2.0.9.RELEASE,
          #1.5.22.RELEASE,
          #1.4.7.RELEASE,
          #1.3.8.RELEASE,
          #1.2.8.RELEASE,
          #1.1.12.RELEASE,
          #1.0.2.RELEASE
        ]
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v3
      # step 2
      - name: "Set up QEMU"
        id: qemu
        uses: docker/setup-qemu-action@v3
      # step 3
      - name: "Build with Maven on 'arm64v8/ubuntu' OS (Skip tests)"
        run: |
          docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
            arm64v8/ubuntu:20.04 \
            bash -exc 'apt-get update -y && \
                       apt-get install maven -y && \
                       mvn -version && \
                       mvn clean install \
                           -Dspring-boot.version=${{ matrix.springboot }} \
                           -Prelease-seata \
                           -DskipTests \
                           -Dmaven.git-commit-id.skip=true \
                           -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
