name: "test"

on:
  push:
    branches: [ arm-binary ]


jobs:     
  test:
    name: "test"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 17 ]
        springboot: [ 2.7.2          -Dspring-framework.version=5.3.22, 2.6.10         -Dspring-framework.version=5.3.22, 2.5.14         -Dspring-framework.version=5.3.20, 2.4.13         -Dspring-framework.version=5.3.13, 2.3.12.RELEASE -Dspring-framework.version=5.2.15.RELEASE, 2.2.13.RELEASE -Dspring-framework.version=5.2.12.RELEASE]
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v2.4.0

      # step 2
      - name: "Set up Java JDK"
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      # step 3
      - name: "Test with Maven"
        # https://docs.github.com/cn/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        run: |
          if [ "${{ matrix.java }}" == "8" ]; then
            ./mvnw -T 4C clean test -Dspring-boot.version=${{ matrix.springboot }} -Dcheckstyle.skip=false -Dlicense.skip=false -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
          else
            ./mvnw -T 4C clean test -Dspring-boot.version=${{ matrix.springboot }} -Dcheckstyle.skip=true  -Dlicense.skip=true  -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
          fi
  test_arm64: 
     runs-on: ubuntu-latest
     strategy:
      matrix:
        java: ["8"]
        springboot: [ 2.7.2          -Dspring-framework.version=5.3.22, 2.6.10         -Dspring-framework.version=5.3.22, 2.5.14         -Dspring-framework.version=5.3.20, 2.4.13         -Dspring-framework.version=5.3.13, 2.3.12.RELEASE -Dspring-framework.version=5.2.15.RELEASE, 2.2.13.RELEASE -Dspring-framework.version=5.2.12.RELEASE]
      fail-fast: false
     steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
      - name: Install and Run tests
        run: |
               docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
               arm64v8/ubuntu:20.04 \
               bash -exc 'apt-get update -y && \
                apt-get install openjdk-8-jdk -y && \
                export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-arm64 && \
                export PATH=$PATH:$JAVA_HOME/bin && \
                echo $PATH && \
                apt-get install maven -y && \
                ./mvnw -T 4C clean test -Dspring-boot.version=${{ matrix.springboot }} -Dcheckstyle.skip=true  -Dlicense.skip=true  -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
